apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: mservice_moderation:0.0.1    

---

apiVersion: v1
kind: Service
metadata: 
  name: moderation-service
spec:
  type: ClusterIP
  selector: 
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4004
      targetPort: 4004  